name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Deploy when changes are pushed to the main branch

permissions:
  contents: write # Grant write access to the repository content for deployment

jobs:
  build:
    name: Build the Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The folder containing the production build
          keep_files: true # Optional: Keep existing files on GitHub Pages
